<?xml version='1.0' encoding='utf-8'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">

    <xacro:property name="link_0_length" value="1"/>
    <xacro:property name="link_1_length" value="1"/>
    <xacro:property name="link_2_length" value="1"/>

    <xacro:property name="link_0_radius" value="0.075"/>
    <xacro:property name="link_1_radius" value="0.075"/>
    <xacro:property name="link_2_radius" value="0.075"/>

    <link name="world"/>

    <joint name="base_joint" type="fixed">
        <parent link="world"/>
        <child link="link0"/>
    </joint>

    <link name="link0">
        <visual>
            <origin xyz="0 0 ${link_0_length / 2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${link_0_length}" radius="${link_0_radius}"/>
            </geometry>
            <material name="orange"/>
        </visual>

        <collision>
            <origin xyz="0 0 ${link_0_length / 2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${link_0_length}" radius="${link_0_radius}"/>
            </geometry>
        </collision>

        <inertial>
            <origin xyz="0 0 ${link_0_length / 2}" rpy="0 0 0"/>
			<mass value="1"/>
			<inertia
			  ixx="0" ixy="0.0" ixz="0.0"
			  iyy="0" iyz="0.0"
			  izz="0"/>
        </inertial>
    </link>

    <link name="link1">
        <visual>
            <origin xyz="0 ${link_0_length/2 + link_0_radius} 0" rpy="1.57 0 0"/>
            <geometry>
                <cylinder length="${link_1_length}" radius="${link_1_radius}"/>
            </geometry>
            <material name="orange"/>
        </visual>

        <collision>
            <origin xyz="0 ${link_0_length/2 + link_0_radius} 0" rpy="1.57 0 0"/>
            <geometry>
                <cylinder length="${link_1_length}" radius="${link_1_radius}"/>
            </geometry>
        </collision>

        <inertial>
            <origin xyz="0 ${link_0_length/2 + link_0_radius} 0" rpy="1.57 0 0"/>
			<mass value="1"/>
			<inertia
			  ixx="0" ixy="0.0" ixz="0.0"
			  iyy="0" iyz="0.0"
			  izz="0"/>
        </inertial>
    </link>

    <link name="link2">
        <visual>
            <origin xyz="0 ${link_1_length/2 + link_0_radius} 0" rpy="1.57 0 0"/>
            <geometry>
                <cylinder length="${link_2_length}" radius="${link_2_radius}"/>
            </geometry>
            <material name="orange"/>
        </visual>

        <collision>
            <origin xyz="0 ${link_1_length/2 + link_0_radius} 0" rpy="1.57 0 0"/>
            <geometry>
                <cylinder length="${link_2_length}" radius="${link_2_radius}"/>
            </geometry>
        </collision>

        <inertial>
            <origin xyz="0 ${link_1_length/2 + link_0_radius} 0" rpy="1.57 0 0"/>
			<mass value="1"/>
			<inertia
			  ixx="0" ixy="0.0" ixz="0.0"
			  iyy="0" iyz="0.0"
			  izz="0"/>
        </inertial>
    </link>

    <joint name="joint1" type="revolute">
      <!-- <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="-2.8973" soft_upper_limit="2.8973"/> -->
      <origin rpy="0 0 0" xyz="0 0 ${link_0_length}"/>
      <parent link="link0"/>
      <child link="link1"/>
      <axis xyz="0 0 1"/>
      <limit effort="87" lower="-2.8973" upper="2.8973" velocity="2.1750"/>
    </joint>

    <joint name="joint2" type="revolute">
      <!-- <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="-2.8973" soft_upper_limit="2.8973"/> -->
      <origin rpy="0 0 0" xyz="0 ${link_1_length} 0"/>
      <parent link="link1"/>
      <child link="link2"/>
      <axis xyz="0 0 1"/>
      <limit effort="87" lower="-2.8973" upper="2.8973" velocity="2.1750"/>
    </joint>

</robot>

